---bài 1---
CREATE DATABASE QUANLYBANHANG

USE QUANLYBANHANG

CREATE TABLE KHACHHANG
(
	MAKH CHAR(4) NOT NULL,
	HOTEN VARCHAR(40),
	DCHI VARCHAR(50),
	SODT VARCHAR(20),
	NGSINH SMALLDATETIME,
	NGDK SMALLDATETIME,
	DOANHSO MONEY,
)

CREATE TABLE NHANVIEN
(
	MANV CHAR(4) NOT NULL,
	HOTEN VARCHAR(40), 
	SODT VARCHAR(20),
	NGVL SMALLDATETIME,
)

CREATE TABLE SANPHAM
(
	MASP CHAR(4) NOT NULL, 
	TENSP VARCHAR(40),
	DVT	VARCHAR(20),
	NUOCSX VARCHAR(40),
	GIA	MONEY,
)

CREATE TABLE HOADON
(
	SOHD INT NOT NULL,
	NGHD SMALLDATETIME,
	MAKH CHAR(4),
	MANV CHAR(4),
	TRIGIA	MONEY,
)

CREATE TABLE CTHD 
(
	SOHD INT NOT NULL,
	MASP CHAR(4) NOT NULL,
	SL INT,
)

---câu 1---
ALTER TABLE KHACHHANG
ALTER COLUMN MAKH char(4) NOT NULL

ALTER TABLE KHACHHANG ADD
CONSTRAINT PK_KH PRIMARY KEY (MAKH)

ALTER TABLE NHANVIEN
ALTER COLUMN MANV char(4) NOT NULL

ALTER TABLE NHANVIEN ADD
CONSTRAINT PK_NV PRIMARY KEY (MANV)

ALTER TABLE SANPHAM
ALTER COLUMN MASP CHAR(4) NOT NULL

ALTER TABLE SANPHAM ADD
CONSTRAINT PK_SP PRIMARY KEY (MASP)

ALTER TABLE HOADON
ALTER COLUMN SOHD INT NOT NULL

ALTER TABLE HOADON ADD
CONSTRAINT PK_HD PRIMARY KEY (SOHD)

ALTER TABLE CTHD
ALTER COLUMN SOHD INT NOT NULL

ALTER TABLE CTHD 
ALTER COLUMN MASP CHAR(4) NOT NULL

ALTER TABLE CTHD ADD
CONSTRAINT PK_CTHD PRIMARY KEY (SOHD, MASP)

ALTER TABLE HOADON ADD
CONSTRAINT FK_HD_KH FOREIGN KEY (MAKH) REFERENCES KHACHHANG (MAKH),
CONSTRAINT FK_HD_NV FOREIGN KEY (MANV) REFERENCES NHANVIEN (MANV)

ALTER TABLE CTHD ADD
CONSTRAINT FK_CTHD_HD FOREIGN KEY (SOHD) REFERENCES HOADON (SOHD),
CONSTRAINT FK_CTHD_SP FOREIGN KEY (MASP) REFERENCES SANPHAM (MASP)


---câu 2---
ALTER TABLE SANPHAM
ADD GHICHU VARCHAR(20)

---câu 3---
ALTER TABLE KHACHHANG
ADD LOAIKH TINYINT

---câu 4---
ALTER TABLE SANPHAM
ALTER COLUMN GHICHU VARCHAR(100)

---câu 5---
ALTER TABLE SANPHAM
drop COLUMN GHICHU

-- câu 6--
ALTER TABLE KHACHHANG
ALTER COLUMN LOAIKH VARCHAR(100)

---câu 7---
ALTER TABLE SANPHAM
ADD CONSTRAINT SP_DVT CHECK (DVT in('cay','hop','cai','quyen','chuc'))

---câu 8---
ALTER TABLE SANPHAM
ADD CONSTRAINT SP_GIA CHECK (GIA >= 500)

---câu 9---
ALTER TABLE CTHD
ADD CONSTRAINT CHTD_SL CHECK (SL>=1)

---câu 10---
ALTER TABLE KHACHHANG
ADD CONSTRAINT KH_NGDKI CHECK(NGDK > NGSINH)











---bài 2---

CREATE DATABASE QuanLyGiaoVu


USE QuanLyGiaoVu



CREATE TABLE KHOA 
(
	MAKHOA VARCHAR(4),
	TENKHOA VARCHAR(40),
	NGTLAP SMALLDATETIME,
	TRGKHOA CHAR(4)
	CONSTRAINT PK_KHOA PRIMARY KEY (MAKHOA)
)


CREATE TABLE MONHOC
(
	MAMH VARCHAR(10),
	TENMH VARCHAR(40),
	TCLT TINYINT,
	TCTH TINYINT,
	MAKHOA VARCHAR(4),
	CONSTRAINT PK_MONHOC PRIMARY KEY (MAMH),
)


CREATE TABLE DIEUKIEN
(
	MAMH VARCHAR(10),
	MAMH_TRUOC VARCHAR(10),
	CONSTRAINT PK_DIEUKIEN PRIMARY KEY (MAMH, MAMH_TRUOC)
)



CREATE TABLE GIAOVIEN
(
	MAGV CHAR(4),
	HOTEN VARCHAR(40),
	HOCVI VARCHAR(10),
	HOCHAM VARCHAR(10),
	GIOITINH VARCHAR(3),
	NGSINH SMALLDATETIME,
	NGVL SMALLDATETIME,
	HESO NUMERIC(4,2),
	MUCLUONG MONEY,
	MAKHOA VARCHAR(4)
	CONSTRAINT PK_GIAOVIEN PRIMARY KEY (MAGV)
)




CREATE TABLE LOP
(
	MALOP CHAR(3),
	TENLOP VARCHAR(40),
	TRGLOP CHAR(5),
	SISO TINYINT,
	MAGVCN CHAR(4)
	CONSTRAINT PK_LOP PRIMARY KEY (MALOP)
)

CREATE TABLE HOCVIEN
(
	MAHV CHAR(5),
	HO VARCHAR(40),
	TEN VARCHAR(10),
	NGSINH SMALLDATETIME,
	GIOITINH VARCHAR(3),
	NOISINH VARCHAR(40),
	MALOP CHAR(3),
	CONSTRAINT PK_HOCVIEN PRIMARY KEY (MAHV)
)

CREATE TABLE GIANGDAY
(
	MALOP CHAR(3),
	MAMH VARCHAR(10),
	MAGV CHAR(4),
	HOCKY TINYINT,
	NAM SMALLINT,
	TUNGAY SMALLDATETIME,
	DENNGAY SMALLDATETIME
	CONSTRAINT PK_GIANGDAY PRIMARY KEY (MALOP, MAMH),
)


CREATE TABLE KETQUATHI
(
	MAHV CHAR(5),
	MAMH VARCHAR(10),
	LANTHI TINYINT,
	NGTHI SMALLDATETIME,
	DIEM NUMERIC(4,2),
	KQUA VARCHAR(10)
	CONSTRAINT PK_KETQUATHI PRIMARY KEY (MAHV, MAMH, LANTHI)
)

ALTER TABLE HOCVIEN ADD CONSTRAINT FK_LOP FOREIGN KEY (MALOP) REFERENCES LOP(MALOP)
ALTER TABLE LOP ADD CONSTRAINT FK_TRGLOP FOREIGN KEY (TRGLOP) REFERENCES HOCVIEN(MAHV)
ALTER TABLE LOP ADD	CONSTRAINT FK_MAGVCN FOREIGN KEY (MAGVCN) REFERENCES GIAOVIEN(MAGV)
ALTER TABLE KHOA ADD CONSTRAINT FK_TRGKHOA FOREIGN KEY (TRGKHOA) REFERENCES GIAOVIEN(MAGV)
ALTER TABLE MONHOC ADD CONSTRAINT FK_MAKHOA FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA)
ALTER TABLE DIEUKIEN ADD CONSTRAINT FK_MAMH_TRUOC FOREIGN KEY (MAMH_TRUOC) REFERENCES MONHOC(MAMH)
ALTER TABLE DIEUKIEN ADD CONSTRAINT FK_MAMH FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH)
ALTER TABLE GIAOVIEN ADD CONSTRAINT FK_MAKHOA_2 FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA)
ALTER TABLE GIANGDAY ADD CONSTRAINT FK_MAMH_2 FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH)
ALTER TABLE GIANGDAY ADD CONSTRAINT FK_MALOP FOREIGN KEY (MALOP) REFERENCES LOP(MALOP)
ALTER TABLE GIANGDAY ADD CONSTRAINT FK_MAGV FOREIGN KEY (MAGV) REFERENCES GIAOVIEN(MAGV)
ALTER TABLE KETQUATHI ADD CONSTRAINT FK_MAHV FOREIGN KEY (MAHV) REFERENCES HOCVIEN(MAHV)
ALTER TABLE KETQUATHI ADD CONSTRAINT FK_MAMH_3 FOREIGN KEY (MAMH) REFERENCES MONHOC (MAMH)

ALTER TABLE HOCVIEN ADD GHICHU VARCHAR(50) 
ALTER TABLE HOCVIEN ADD DIEMTB NUMERIC(4,2)
ALTER TABLE HOCVIEN ADD XEPLOAI VARCHAR(50)

--- CÂU 3---
ALTER TABLE GIAOVIEN ADD CONSTRAINT CHECK_GTGV CHECK (GIOITINH IN('NAM','NU'))
ALTER TABLE HOCVIEN ADD CONSTRAINT CHECK_GTHV CHECK (GIOITINH IN('NAM', 'NU'))

--CAU4
ALTER TABLE KETQUATHI ADD CONSTRAINT CHECK_DIEM CHECK 
(
	DIEM BETWEEN 0 AND 10
	AND RIGHT(CAST(DIEM AS VARCHAR), 3) LIKE '.__'
)
--CAU5
ALTER TABLE KETQUATHI ADD CONSTRAINT CHECK_KETQUA CHECK
(	
	(KQUA = 'Dat' AND DIEM BETWEEN 5 AND 10)
	OR (KQUA = 'Khong dat' AND DIEM < 5)
)

--CAU6
ALTER TABLE KETQUATHI ADD CONSTRAINT CHECK_LANTHI CHECK (LANTHI <= 3)

--CAU7
ALTER TABLE GIANGDAY ADD CONSTRAINT CHECK_HOCKY CHECK (HOCKY BETWEEN 1 AND 3)

--CAU8
ALTER TABLE GIAOVIEN ADD CONSTRAINT CHECK_HOCVI CHECK (HOCVI IN ('CN', 'KS', 'Ths', 'TS', 'PTS'))
